"""Rule tables of the identity engine: roles, process, image, header and port rules.

Data only; :mod:`lirts.identity` applies them and re-exports the role constants.
What a web response or a compose service name reveals lives next door in
:mod:`lirts.identity_rules_web`.
"""

from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    """What kind of service a listener is, as far as identity can tell."""

    FRONTEND = "frontend"
    BACKEND = "backend"
    DB = "db"
    CACHE = "cache"
    PROXY = "proxy"
    QUEUE = "queue"
    DOCKER = "docker"
    SYSTEM = "system"
    TOOL = "tool"
    TUNNEL = "tunnel"
    SSH = "ssh"
    UNKNOWN = "unknown"


ROLE_FRONTEND = Role.FRONTEND
ROLE_BACKEND = Role.BACKEND
ROLE_DB = Role.DB
ROLE_CACHE = Role.CACHE
ROLE_PROXY = Role.PROXY
ROLE_QUEUE = Role.QUEUE
ROLE_DOCKER = Role.DOCKER
ROLE_SYSTEM = Role.SYSTEM
ROLE_TOOL = Role.TOOL
ROLE_TUNNEL = Role.TUNNEL
ROLE_UNKNOWN = Role.UNKNOWN

# Human labels for roles, as shown in the table and the side panel.
ROLE_LABELS: dict[str, str] = {
    ROLE_FRONTEND: "frontend",
    ROLE_BACKEND: "backend",
    ROLE_DB: "database",
    ROLE_CACHE: "cache",
    ROLE_PROXY: "proxy",
    ROLE_QUEUE: "queue",
    ROLE_DOCKER: "docker",
    ROLE_SYSTEM: "system",
    ROLE_TOOL: "tool",
    ROLE_TUNNEL: "tunnel",
    Role.SSH: "ssh",
    ROLE_UNKNOWN: "unknown",
}

# (process-name regex, command-line regex or None, service, role, confidence)
PROCESS_RULES: list[tuple[str, str | None, str, str, float]] = [
    (r"^postgres|^postmaster", None, "PostgreSQL", ROLE_DB, 0.95),
    (r"^redis-server|^valkey", None, "Redis", ROLE_CACHE, 0.95),
    (r"^mysqld|^mariadbd", None, "MySQL / MariaDB", ROLE_DB, 0.95),
    (r"^mongod", None, "MongoDB", ROLE_DB, 0.95),
    (r"^memcached", None, "Memcached", ROLE_CACHE, 0.95),
    (r"^clickhouse", None, "ClickHouse", ROLE_DB, 0.9),
    (r"^influxd", None, "InfluxDB", ROLE_DB, 0.9),
    (r"^minio", None, "MinIO", ROLE_DB, 0.9),
    (r"^nginx", None, "Nginx", ROLE_PROXY, 0.95),
    (r"^httpd|^apache2", None, "Apache httpd", ROLE_PROXY, 0.9),
    (r"^caddy", None, "Caddy", ROLE_PROXY, 0.95),
    (r"^traefik", None, "Traefik", ROLE_PROXY, 0.95),
    (r"^haproxy", None, "HAProxy", ROLE_PROXY, 0.95),
    (r"^envoy", None, "Envoy", ROLE_PROXY, 0.95),
    (r"^ngrok", None, "ngrok tunnel", ROLE_PROXY, 0.9),
    (r"^cloudflared", None, "Cloudflare tunnel", ROLE_PROXY, 0.9),
    (r"^php-fpm", None, "PHP-FPM", ROLE_BACKEND, 0.95),
    (r"^php$", r"artisan\s+serve", "Laravel dev server", ROLE_BACKEND, 0.95),
    (r"^php$", r"\s-S\s", "PHP built-in server", ROLE_BACKEND, 0.9),
    (r"^beam\.smp|^erl", r"rabbit", "RabbitMQ", ROLE_QUEUE, 0.95),
    (r"^beam\.smp|^erl", r"phx|phoenix|mix", "Phoenix (Elixir)", ROLE_BACKEND, 0.9),
    (r"^mosquitto", None, "Mosquitto MQTT", ROLE_QUEUE, 0.95),
    (r"^nats-server", None, "NATS", ROLE_QUEUE, 0.95),
    (r"^java", r"kafka", "Kafka", ROLE_QUEUE, 0.9),
    (r"^java", r"elasticsearch|opensearch", "Elasticsearch", ROLE_DB, 0.9),
    (r"^java", r"tomcat|catalina", "Tomcat", ROLE_BACKEND, 0.85),
    (r"^java", r"spring|\.jar", "Java app", ROLE_BACKEND, 0.7),
    (r"^java", r"gradle", "Gradle daemon", ROLE_TOOL, 0.85),
    (r"^node|^bun|^deno", r"\bvite\b", "Vite dev server", ROLE_FRONTEND, 0.95),
    (r"^node|^bun", r"next(\s|/|-)|\bnext\b.*\bdev\b", "Next.js dev server", ROLE_FRONTEND, 0.95),
    (r"^node|^bun", r"\bnuxt\b", "Nuxt dev server", ROLE_FRONTEND, 0.95),
    (r"^node|^bun", r"\bastro\b", "Astro dev server", ROLE_FRONTEND, 0.95),
    (r"^node|^bun", r"\bremix\b", "Remix dev server", ROLE_FRONTEND, 0.9),
    (r"^node|^bun", r"\bsvelte(kit)?\b", "SvelteKit dev server", ROLE_FRONTEND, 0.9),
    (
        r"^node|^bun",
        r"react-scripts|webpack-dev-server|webpack",
        "Webpack dev server",
        ROLE_FRONTEND,
        0.9,
    ),
    (r"^node|^bun", r"\bng\b.*serve|angular", "Angular dev server", ROLE_FRONTEND, 0.9),
    (r"^node|^bun", r"storybook", "Storybook", ROLE_FRONTEND, 0.9),
    (r"^node|^bun", r"\bexpo\b|metro", "Expo / Metro bundler", ROLE_FRONTEND, 0.9),
    (r"^node|^bun", r"\bstrapi\b", "Strapi", ROLE_BACKEND, 0.9),
    (r"^node|^bun", r"\bnest\b", "NestJS", ROLE_BACKEND, 0.85),
    (r"^node|^bun", r"\bexpress\b", "Express (Node.js)", ROLE_BACKEND, 0.8),
    (r"^node|^bun", r"prisma\s+studio", "Prisma Studio", ROLE_TOOL, 0.9),
    (r"^node|^bun", r"nodemon|ts-node|tsx\b", "Node.js app (dev)", ROLE_BACKEND, 0.75),
    (r"^node|^bun|^deno", r"\.(m?js|ts)\b", "Node.js app", ROLE_BACKEND, 0.6),
    (r"^node|^bun|^deno", None, "Node.js app", ROLE_BACKEND, 0.5),
    (
        r"^python|^uvicorn|^gunicorn|^hypercorn",
        r"manage\.py\s+runserver",
        "Django dev server",
        ROLE_BACKEND,
        0.95,
    ),
    (r"^python|^uvicorn|^hypercorn", r"uvicorn|hypercorn", "ASGI app (uvicorn)", ROLE_BACKEND, 0.9),
    (r"^python|^gunicorn", r"gunicorn", "Gunicorn (WSGI)", ROLE_BACKEND, 0.9),
    (r"^python|^flask", r"\bflask\b", "Flask dev server", ROLE_BACKEND, 0.9),
    (r"^python", r"fastapi", "FastAPI", ROLE_BACKEND, 0.9),
    (r"^python|^streamlit", r"streamlit", "Streamlit", ROLE_TOOL, 0.95),
    (r"^python|^jupyter", r"jupyter|ipykernel", "Jupyter", ROLE_TOOL, 0.95),
    (r"^python", r"mkdocs|sphinx", "Docs server", ROLE_TOOL, 0.9),
    (r"^python", r"http\.server|SimpleHTTPServer", "Python static server", ROLE_TOOL, 0.95),
    (r"^python", r"celery", "Celery", ROLE_BACKEND, 0.9),
    (r"^python", r"textual|lirts", "Textual app", ROLE_TOOL, 0.8),
    (r"^python", None, "Python app", ROLE_BACKEND, 0.45),
    (r"^ruby|^puma|^unicorn", r"rails|puma|unicorn", "Rails", ROLE_BACKEND, 0.9),
    (r"^ruby", r"jekyll", "Jekyll", ROLE_FRONTEND, 0.9),
    (r"^dotnet", None, ".NET app", ROLE_BACKEND, 0.7),
    (r"^hugo", None, "Hugo dev server", ROLE_FRONTEND, 0.95),
    (r"^ollama", None, "Ollama", ROLE_TOOL, 0.95),
    (r"^code|^Code Helper|^code-server|^Code$", None, "VS Code", ROLE_TOOL, 0.85),
    (r"^Cursor", None, "Cursor", ROLE_TOOL, 0.85),
    (
        r"^pycharm|^idea|^webstorm|^phpstorm|^goland|^rider|^clion|^datagrip|^fleet",
        None,
        "JetBrains IDE",
        ROLE_TOOL,
        0.85,
    ),
    (r"^java", r"jetbrains|intellij|pycharm|webstorm", "JetBrains IDE", ROLE_TOOL, 0.85),
    (r"^Claude", None, "Claude desktop app", ROLE_TOOL, 0.85),
    (r"^Google Chrome|^Chrome|^chrome", None, "Google Chrome", ROLE_TOOL, 0.85),
    (r"^Safari|^Firefox|^firefox|^Arc|^Brave", None, "Web browser", ROLE_TOOL, 0.85),
    (
        r"^Spotify|^Slack|^Discord|^Dropbox|^1Password|^Figma|^Notion|^zoom|^Teams",
        None,
        "Desktop app",
        ROLE_TOOL,
        0.8,
    ),
    (r"^Electron", None, "Electron app", ROLE_TOOL, 0.6),
    (r"^jetbrains-toolbox", None, "JetBrains Toolbox", ROLE_TOOL, 0.9),
    (r"^logioptionsplus|^logi", None, "Logitech Options+", ROLE_TOOL, 0.85),
    (r"^Raycast|^Alfred|^BetterTouchTool|^Karabiner", None, "Desktop utility", ROLE_TOOL, 0.85),
    (r"^Adobe|^Creative Cloud|^CoreSync", None, "Adobe app", ROLE_TOOL, 0.85),
    (r"^Steam|^EpicGames", None, "Game launcher", ROLE_TOOL, 0.85),
    (r"^Postman|^Insomnia|^Bruno", None, "API client", ROLE_TOOL, 0.9),
    (r"^Docker Desktop|^Docker$", None, "Docker Desktop", ROLE_DOCKER, 0.9),
    (r"^OrbStack|^orbstack", None, "OrbStack", ROLE_DOCKER, 0.9),
    (r"^(.+) Helper|^(.+)Helper", None, "App helper process", ROLE_TOOL, 0.4),
    (r"agent$|daemon$", None, "Background daemon", ROLE_SYSTEM, 0.3),
    (r"^syncthing", None, "Syncthing", ROLE_TOOL, 0.95),
    (r"^prometheus", None, "Prometheus", ROLE_TOOL, 0.95),
    (r"^grafana", None, "Grafana", ROLE_TOOL, 0.95),
    (r"^mailhog|^mailpit|^MailHog", None, "Mail catcher", ROLE_TOOL, 0.95),
    (r"^sshd|^ssh$", None, "SSH server", ROLE_SYSTEM, 0.95),
    (r"^cupsd", None, "CUPS printing", ROLE_SYSTEM, 0.95),
    (r"^tailscaled|^Tailscale", None, "Tailscale", ROLE_SYSTEM, 0.95),
    (
        r"^com\.docker\.backend|^docker-proxy|^vpnkit|^com\.docker",
        None,
        "Docker port proxy",
        ROLE_DOCKER,
        0.9,
    ),
    (r"^dockerd|^containerd", None, "Docker daemon", ROLE_DOCKER, 0.9),
    (r"^colima|^limactl|^qemu|^podman", None, "Container VM", ROLE_DOCKER, 0.85),
    (r"^kubelet|^kube-|^k3s|^minikube", None, "Kubernetes", ROLE_DOCKER, 0.85),
    (r"^systemd-resolve|^dnsmasq|^named|^unbound", None, "DNS resolver", ROLE_SYSTEM, 0.9),
    (r"^avahi|^mDNSResponder", None, "mDNS / Bonjour", ROLE_SYSTEM, 0.95),
    (
        r"^rapportd|^ControlCe|^sharingd|^airplay|^AirPlay|^identityservice|^wifip2pd|^WiFiAgent|^apsd|^bluetoothd|^remoted|^launchd|^remotepairingd|^UserEventAgent|^ContinuityCaptureAgent|^universalaccessd|^AMPDevices|^ScreensharingAgent|^screensharingd|^netbiosd|^Music$|^Photos$|^Finder$|^nesessionmanager|^locationd|^searchpartyd|^timed|^assistantd|^CommCenter|^callservicesd|^cloudd|^akd|^rtcreportingd|^audioclocksyncd|^adprivacyd|^appleaccountd|^SystemUIServer|^Dock$",
        None,
        "macOS system service",
        ROLE_SYSTEM,
        0.85,
    ),
    (
        r"^systemd|^NetworkManager|^cups-browsed|^chronyd|^ntpd|^rpcbind|^rpc\.|^xrdp|^gnome|^pipewire|^wireplumber|^kdeconnect",
        None,
        "Linux system service",
        ROLE_SYSTEM,
        0.85,
    ),
    (r"^go$|^main$|^__debug_bin|^air$", None, "Go app", ROLE_BACKEND, 0.5),
    (r"^cargo|^target/", None, "Rust app", ROLE_BACKEND, 0.5),
]

IMAGE_RULES: list[tuple[str, str, str]] = [
    (r"postgres|postgis|timescale|pgvector", "PostgreSQL", ROLE_DB),
    (r"redis|valkey", "Redis", ROLE_CACHE),
    (r"mysql|mariadb|percona", "MySQL / MariaDB", ROLE_DB),
    (r"mongo", "MongoDB", ROLE_DB),
    (r"memcached", "Memcached", ROLE_CACHE),
    (r"clickhouse", "ClickHouse", ROLE_DB),
    (r"influx", "InfluxDB", ROLE_DB),
    (r"elasticsearch|opensearch", "Elasticsearch", ROLE_DB),
    (r"meilisearch|typesense", "Search engine", ROLE_DB),
    (r"minio", "MinIO", ROLE_DB),
    (r"neo4j|surrealdb|couchdb|cockroach|scylla|cassandra|dynamodb", "Database", ROLE_DB),
    (r"nginx", "Nginx", ROLE_PROXY),
    (r"traefik", "Traefik", ROLE_PROXY),
    (r"caddy", "Caddy", ROLE_PROXY),
    (r"haproxy", "HAProxy", ROLE_PROXY),
    (r"httpd|apache", "Apache httpd", ROLE_PROXY),
    (r"rabbitmq", "RabbitMQ", ROLE_QUEUE),
    (r"kafka|redpanda", "Kafka", ROLE_QUEUE),
    (r"nats", "NATS", ROLE_QUEUE),
    (r"mosquitto|emqx|hivemq", "MQTT broker", ROLE_QUEUE),
    (r"mailhog|mailpit|maildev", "Mail catcher", ROLE_TOOL),
    (
        r"adminer|phpmyadmin|pgadmin|mongo-express|redis-commander|redisinsight",
        "DB admin UI",
        ROLE_TOOL,
    ),
    (r"grafana|prometheus|jaeger|zipkin|kibana|loki|tempo", "Observability", ROLE_TOOL),
    (r"localstack|minio", "Local cloud emulator", ROLE_TOOL),
    (r"keycloak|authentik|ory", "Auth server", ROLE_BACKEND),
    (r"wordpress|drupal|ghost", "CMS", ROLE_BACKEND),
    (r"ollama", "Ollama", ROLE_TOOL),
    (r"php", "PHP app", ROLE_BACKEND),
    (r"node|bun|deno", "Node.js app", ROLE_BACKEND),
    (r"python|django|flask|fastapi|uvicorn", "Python app", ROLE_BACKEND),
    (r"golang|/go:|^go:", "Go app", ROLE_BACKEND),
    (r"openjdk|eclipse-temurin|amazoncorretto|tomcat", "Java app", ROLE_BACKEND),
    (r"dotnet|aspnet", ".NET app", ROLE_BACKEND),
    (r"ruby|rails", "Ruby app", ROLE_BACKEND),
]

HEADER_RULES: list[tuple[str, str, str]] = [
    (r"nginx", "Nginx", ROLE_PROXY),
    (r"apache", "Apache httpd", ROLE_PROXY),
    (r"caddy", "Caddy", ROLE_PROXY),
    (r"traefik", "Traefik", ROLE_PROXY),
    (r"envoy", "Envoy", ROLE_PROXY),
    (r"express", "Express (Node.js)", ROLE_BACKEND),
    (r"next\.js", "Next.js", ROLE_FRONTEND),
    (r"nuxt", "Nuxt", ROLE_FRONTEND),
    (r"kestrel", ".NET Kestrel", ROLE_BACKEND),
    (r"werkzeug", "Flask / Werkzeug", ROLE_BACKEND),
    (r"uvicorn", "ASGI app (uvicorn)", ROLE_BACKEND),
    (r"gunicorn", "Gunicorn (WSGI)", ROLE_BACKEND),
    (r"wsgiserver|cheroot", "WSGI app", ROLE_BACKEND),
    (r"jetty|tomcat|undertow", "Java web app", ROLE_BACKEND),
    (r"cowboy", "Phoenix / Cowboy", ROLE_BACKEND),
    (r"puma|unicorn|webrick", "Ruby web app", ROLE_BACKEND),
    (r"php", "PHP app", ROLE_BACKEND),
    (r"simplehttp|baseHTTP", "Python static server", ROLE_TOOL),
    (r"tornadoserver", "Tornado / Jupyter", ROLE_TOOL),
    (r"minio", "MinIO", ROLE_DB),
    (r"grafana", "Grafana", ROLE_TOOL),
    (r"ollama", "Ollama", ROLE_TOOL),
    (r"esphome|home assistant", "Home automation", ROLE_TOOL),
]

KNOWN_PORTS: dict[int, tuple[str, str]] = {
    21: ("FTP", ROLE_SYSTEM),
    22: ("SSH", ROLE_SYSTEM),
    25: ("SMTP", ROLE_SYSTEM),
    53: ("DNS", ROLE_SYSTEM),
    80: ("HTTP server", ROLE_PROXY),
    88: ("Kerberos", ROLE_SYSTEM),
    110: ("POP3", ROLE_SYSTEM),
    143: ("IMAP", ROLE_SYSTEM),
    443: ("HTTPS server", ROLE_PROXY),
    445: ("SMB", ROLE_SYSTEM),
    631: ("CUPS printing", ROLE_SYSTEM),
    1025: ("SMTP (dev)", ROLE_TOOL),
    1080: ("SOCKS proxy", ROLE_PROXY),
    1433: ("SQL Server", ROLE_DB),
    1521: ("Oracle DB", ROLE_DB),
    1883: ("MQTT broker", ROLE_QUEUE),
    2181: ("ZooKeeper", ROLE_QUEUE),
    2375: ("Docker API", ROLE_DOCKER),
    2376: ("Docker API (TLS)", ROLE_DOCKER),
    3000: ("Node.js app", ROLE_BACKEND),
    3001: ("Node.js app", ROLE_BACKEND),
    3306: ("MySQL", ROLE_DB),
    3389: ("RDP", ROLE_SYSTEM),
    4000: ("Dev server", ROLE_BACKEND),
    4200: ("Angular dev server", ROLE_FRONTEND),
    4321: ("Astro dev server", ROLE_FRONTEND),
    4444: ("Selenium", ROLE_TOOL),
    5000: ("Flask / AirPlay", ROLE_BACKEND),
    5001: ("Dev server", ROLE_BACKEND),
    5173: ("Vite dev server", ROLE_FRONTEND),
    5174: ("Vite dev server", ROLE_FRONTEND),
    5353: ("mDNS", ROLE_SYSTEM),
    5432: ("PostgreSQL", ROLE_DB),
    5433: ("PostgreSQL", ROLE_DB),
    5555: ("Prisma Studio / Flower", ROLE_TOOL),
    5672: ("AMQP (RabbitMQ)", ROLE_QUEUE),
    5900: ("VNC", ROLE_SYSTEM),
    6006: ("Storybook", ROLE_FRONTEND),
    6379: ("Redis", ROLE_CACHE),
    6380: ("Redis", ROLE_CACHE),
    6443: ("Kubernetes API", ROLE_DOCKER),
    7000: ("AirPlay / dev server", ROLE_SYSTEM),
    7700: ("Meilisearch", ROLE_DB),
    8000: ("Python web app", ROLE_BACKEND),
    8001: ("Python web app", ROLE_BACKEND),
    8025: ("Mail catcher UI", ROLE_TOOL),
    8080: ("HTTP alt", ROLE_BACKEND),
    8081: ("HTTP alt", ROLE_BACKEND),
    8086: ("InfluxDB", ROLE_DB),
    8123: ("ClickHouse HTTP", ROLE_DB),
    8443: ("HTTPS alt", ROLE_PROXY),
    8888: ("Jupyter", ROLE_TOOL),
    9000: ("PHP-FPM / MinIO", ROLE_BACKEND),
    9090: ("Prometheus", ROLE_TOOL),
    9092: ("Kafka", ROLE_QUEUE),
    9200: ("Elasticsearch", ROLE_DB),
    9229: ("Node.js inspector", ROLE_TOOL),
    11211: ("Memcached", ROLE_CACHE),
    11434: ("Ollama", ROLE_TOOL),
    15672: ("RabbitMQ UI", ROLE_TOOL),
    27017: ("MongoDB", ROLE_DB),
}

_PROJECT_PARENTS = {
    "development",
    "developer",
    "dev",
    "projects",
    "project",
    "src",
    "code",
    "repos",
    "repo",
    "git",
    "work",
    "workspace",
    "workspaces",
    "sites",
    "www",
    "apps",
    "go",
    "documents",
}
_NOT_PROJECTS = {
    "",
    "/",
    "node_modules",
    "bin",
    "tmp",
    "var",
    "usr",
    "opt",
    "library",
    "applications",
}
